### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sareh** [bbc/grandstand#67]
- [ ] `How to get started.md` just by using the `/dist/grandstand.css` file
- [ ] `How to contribute.md` - what to include in a PR, that we use Semver (+ examples). how to release afterwards (if a core contributor).

- [ ] `Why have Settings, Objects, Components?` aka why ITCSS?

- [ ] Settings - Global
- [ ] Settings - Scripts

For these: a short explanation, then markup + a screenshot of the output. 
- [x] [Objects - bullet](https://github.com/bbc/grandstand/blob/master/lib/objects/_bullet.scss)
- [x] [Objects - button](https://github.com/bbc/grandstand/blob/master/lib/objects/_button.scss)
- [x] [Objects - faux-block-link](https://github.com/bbc/grandstand/blob/master/lib/objects/_faux-block-link.scss)
- [x] [Objects - flag](https://github.com/bbc/grandstand/blob/master/lib/objects/_flag.scss)
- [x] [Objects - icons](https://github.com/bbc/grandstand/blob/master/lib/objects/_icons.scss)
- [x] [Objects - list-inline](https://github.com/bbc/grandstand/blob/master/lib/objects/_list-inline.scss)
- [ ] [Objects - list-ui](https://github.com/bbc/grandstand/blob/master/lib/objects/_list-ui.scss)
- [ ] [Objects - media-island](https://github.com/bbc/grandstand/blob/master/lib/objects/_media-island.scss)
- [ ] [Objects - media](https://github.com/bbc/grandstand/blob/master/lib/objects/_media.scss)
- [ ] [Objects - responsive-image](https://github.com/bbc/grandstand/blob/master/lib/objects/_responsive-image.scss)
- [ ] [Objects - table](https://github.com/bbc/grandstand/blob/master/lib/objects/_table.scss)

- [ ] Sass Mixins https://github.com/bbc/gs-sass-tools/tree/master/tools 
- [ ] Sass Colour variables https://github.com/bbc/gs-sass-tools/tree/master/settings

- [ ] Typography 
- [ ] Grid - `gel-grid` plus addition of 1280-specific classes
- [ ] Icons - dealing with them on a case-by-case basis

**Comment by stuartmemo** [comment]
Hi @sareh, is there any way to see screenshots of the components you've already documented?

**Comment by lukejpreston** [comment]
I am doing some innovation and part of it was to understand more about grandstand. I have started created documentation which is similar to http://bulma.io

please checkout out the code and open one of the html files in the docs folder. It does not require the internet and uses no JavaScript
